### ISSUE TITLE
bash disown job control causes recurring IPC error

### ISSUE THREAD

**Issue by qrkourier** [openziti/desktop-edge-ui#1]
![image](https://user-images.githubusercontent.com/1434400/190485680-7e3cdf94-c57b-4566-99a7-eed205d14e27.png)

Steps to reproduce:

```bash
npm start &
disown
exit
```

**Comment by JeremyTellier** [comment]
These errors should now pop into a growler view.

**Comment by qrkourier** [comment]
I no longer get that error popup but I also can't figure out how to background node. It always hangs.
