### ISSUE TITLE
mission control inaccurate while no tunneler running

### ISSUE THREAD

**Issue by qrkourier** [openziti/desktop-edge-ui#116]
I left the app running while I stopped the tunnel to troubleshoot something else. The app's mission control keeps showing inaccurate info after stopping the tunnel.

App: 3.2.1 (from DEB)
Service: v0.21.0 (from DEB)

One identity was loaded before I stopped the tunnel, and that identity did not have MFA enabled. The download and upload activity appear stuck at 1 kbps.

![image](https://user-images.githubusercontent.com/1434400/236301323-8c1498c5-44bf-4f4b-9c9c-c047cf080caa.png)

**Comment by JeremyTellier** [comment]
Fixed with state handler in 3.2.8
