### ISSUE TITLE
windows 10 install notes

### ISSUE THREAD

**Issue by qrkourier** [openziti/desktop-edge-ui#124]
I got it working on win 10 by running the installer exe as administrator. The first attempt failed without any errors even though it prompted for UAC while the installer was running. The result of that first attempt was the ZitiDesktopEdge (preview) app wasn't available in the start menu.

I had to start the tunnel service by pushing the button, and that woke up the other ZDEW UI too. It seems like they're synchronized because the same identities are available in both and so they seem to be using the same tunnel service. I'm not sure if I'll have problems running them concurrently, but a spot check of an intercept is working normally.

**Comment by JeremyTellier** [comment]
They are using the same tunneller service, looking to make the new UI pull the main service in the next installer but the preview UI expects the service to be installed already
