### ISSUE TITLE
taskbar icon needs to be filled - not transparent

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-ui#23]
on a dark background it's almost invisible:
![image](https://user-images.githubusercontent.com/46322585/195706897-b427c089-1fb3-4464-94e7-577044e1b3a8.png)

**Comment by davefinger** [comment]
@JeremyTellier is working on this one. It will be white if you're in dark mode and black if you're in normal. It also has states for connection, etc.
