### ISSUE TITLE
can't toggle on/off individual identities

### ISSUE THREAD

**Issue by qrkourier** [openziti/desktop-edge-ui#3]
There's no error in the UI and the toggle off seems to succeed but the identity is still enabled if I close the UI and return to list of identities.

This may be a known issue with `ziti-edge-tunnel on_off_identity` mentioned in issue https://github.com/openziti/ziti-tunnel-sdk-c/issues/493

**Comment by JeremyTellier** [comment]
This was probably not implemented at the time of the comment, it is working now, or at least should be .

**Comment by qrkourier** [comment]
I pulled latest and got ZitiDesktopEdge@3.0.0 and in this version I'm still not able to toggle identities. I've only tried to activate the one inactive identity I have.
