### ISSUE TITLE
remember the size of the screen

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-ui#30]
i find the default window size to be "too large". Can we have a setting that lets me save the size of the screen so the next time it opens it's not 'ginormous'?

**Comment by qrkourier** [comment]
For some reason this particular app always opens with an extremely large and extra wide shape on my primary display which has a geometry of 21:9 ultrawide. It makes no difference what was the most recent shape when I closed the app or which display it was on when I closed it. Observed with 3.0.2 on Linux.

**Comment by JeremyTellier** [comment]
I will add a "Max Size" for open right now it does like 80% of the screen

**Comment by JeremyTellier** [comment]
Size is maintained between sessions now
