### ISSUE TITLE
mission control should be collapsable to 'smaller' view

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-ui#36]
particularly on the identities view, i'd like to be able to get more real estate in the identities column and less on 'misssion control'

![image](https://user-images.githubusercontent.com/46322585/196472261-1f9cacab-b7e6-48b8-b5a8-11daf7e469ad.png)

**Comment by JeremyTellier** [comment]
@davefinger Can you mock up what it would look like if we minimized the left nav bar to just icons like ZAC does or NF console used to

**Comment by davefinger** [comment]
I don't like the idea of collapsing that pane @JeremyTellier. It's not designed for that and contains the stop/start button, update notifications, and a bunch of other stuff.  We can probably reduce the width of that menu by getting right off the word 'advanced' and just go with 'settings'. Should give us another 100px in the identity column. Beyond that, that's what the full-screen button is for, or dragging the window wider.
