### ISSUE TITLE
the selected logging level is 'far' from the value.

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-ui#39]
it'd be nice to have a selected value color as well as the radio button. also it'd be nice to have a 'you can click anywhere to select' hover not just the radio

![image](https://user-images.githubusercontent.com/46322585/196474659-29e9a17a-6b97-42af-901e-74d33c758739.png)

**Comment by JeremyTellier** [comment]
New selected outline and hover states in latest commit
