### ISSUE TITLE
rearrange services page

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-ui#42]
move ports/protocols to the bottom and addresses to the bottom of the 6 panels, moving posture checks/identity 'above'. then allow the ports/address to flow better. perhaps stack the ports/addresses? UX needs to have boundaries pushed to find ugliness :) super long addresses, 100 addresses on a service, 100 ports on a service

![image](https://user-images.githubusercontent.com/46322585/196475445-55bf2a77-91b3-49cf-aae1-c673a2597859.png)

**Comment by JeremyTellier** [comment]
Complete in Commit #6174ea7
