### ISSUE TITLE
mfa/forget identity button should be easier to find

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-ui#44]
when there's a single service (or a handful) it's nbd. forget identity is 'right there' (though i assert it's kinda ugly/offputting when you have NO services (as shown)
![image](https://user-images.githubusercontent.com/46322585/197198410-e2f860c3-46e8-468b-ade7-f7b0c9063d44.png)

If you have MANY services.. it's way at the bottom of your list. I don't think it should be way down there. you can see i had to scroll a long way to find the 'forget' button. same for 'mfa'

![image](https://user-images.githubusercontent.com/46322585/197198591-d38a10b7-ac8b-438d-b3b1-2efd2d6a2a51.png)

**Comment by JeremyTellier** [comment]
I think this is suppose to stick to the bottom. Its a bug
