### ISSUE TITLE
support / give feedback privilege escalation gets stuck

### ISSUE THREAD

**Issue by qrkourier** [openziti/desktop-edge-ui#7]
The app gets stuck waiting for permission to generate the feedback package if the password prompt is canceled. While it's stuck the user may navigate way from the support / give feedback page while the rainbow progress ribbon animates at the bottom and the "generate" button remains disabled.

![2022-10-05_13-25](https://user-images.githubusercontent.com/1434400/194123820-d929f529-d27f-4676-8371-0b65a743c4de.png)

**Comment by JeremyTellier** [comment]
Same as Issue #8
