### ISSUE TITLE
support / give feedback / generate button asks for root without explanation

### ISSUE THREAD

**Issue by qrkourier** [openziti/desktop-edge-ui#8]
The app asks for root escalation to generate the feedback package, but doesn't say precisely what it's going to collect or change and doesn't offer any alternatives. It would go far to inspire confidence if the text near the button made it perfectly clear what files would be collected and how the feedback package will be handled. Is it going to immediately upload to someone's cloud or will a file be generated that I can first inspect before sharing? A welcome alternative would be steps to generate the package after an opportunity to inspect the script. The password prompt asks for permission to run "bash" which is slightly alarming. I decided not to proceed when I saw that for the reasons above.

![2022-10-05_13-30](https://user-images.githubusercontent.com/1434400/194124678-e1d1e399-32e1-4764-aa59-89fd238b1dae.png)

**Comment by JeremyTellier** [comment]
Linux actually doesn't have a service to generate that package, I hid this in the latest commit until one gets added
