### ISSUE TITLE
What is the meaning of the PASS value next to services in the main Services screen?

### ISSUE THREAD

**Issue by qrkourier** [openziti/desktop-edge-ui#9]
![2022-10-05_13-37](https://user-images.githubusercontent.com/1434400/194125509-88e634f6-1aec-4af6-9b2e-13ebae7f9457.png)

**Comment by JeremyTellier** [comment]
This is only suppose to show if posture checks are available, I have fixed that, PASS means they are passing the checks FAIL means they are failing.
